Attempt to correct dyld: Symbol not found __ZN7nsDebug9AssertionEPKcS1_S1_i in VBoxXPCOM.dylib, similar to changes in r125944
git-svn-id: https://www.virtualbox.org/svn/vbox/trunk@74935 cfe28804-0f27-0410-a406-dd0f0b0b656f